영화리뷰/devsns/devsns/urls.py
from django.contrib import admin
from django.urls import path, include
from snsapp import views
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('postcreate/', views.postcreate, name='postcreate'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),

    path('login/', accounts_views.login, name='login'),
    path('logout/', accounts_views.logout, name='logout'),
    path('signup/', accounts_views.signup, name='signup'),

    path('freehome/', views.freehome, name='freehome'),
    path('freepostcreate/', views.freepostcreate, name='freepostcreate'),
    path('freedetail/<int:post_id>', views.freedetail, name='freedetail'),
    path('new_freecomment/<int:post_id>', views.new_freecomment, name='new_freecomment'),
    
    path('accounts/', include('allauth.urls')),
    path('stat/', views.stat, name='stat'),
     path('polls/', include('polls.urls')),
    
] 
# 미디어 파일 접근을 위해서
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

영화리뷰/devsns/snsapp/models.py
from distutils.command.upload import upload
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# 익명게시판 모델
class Post(models.Model):
    #id는 내부에서 만들어줌

    title = models.CharField(max_length=200)
    body = models.TextField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(blank=True, null=True, upload_to='blog_photo')

    Type=(
        ('D', 'Dresses'),
        ('M', 'Blouses & Shirts'),
        ('C', 'Coats'),
        ('B', 'Bombers'),
        ('T', 'T-shirts & Sweaters'),
        ('S', 'Sweatshirts'),
        ('Car', 'Cardigans & Sweaters'),
        ('J','Jackets'),
        ('T', 'Trousers'),
        ('Je','Jeans'),
        ('S', 'Shorts')
    )
    cloth_type = models.CharField(max_length=20,choices=Type, default='')


    def __str__(self):
        return self.title #admin page에 어떻게 나타나
        
# 익명게시판 댓글 모델
class Comment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE) 
    # 코멘트는 포스트에 종속되어있기때문에 forignkey로 불러옴
    # on_delete=models.CASCADE 글이 삭제되면 같이 삭제될거다
    def __str__(self):
        return self.comment

# 자유게시판 모델
class FreePost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    # 유저객체를 참조하는 컬럼
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

# 자유게시판 댓글 모델
class FreeComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField()
    post = models.ForeignKey(FreePost, null=True, blank=True, on_delete=models.CASCADE) 
    
    def __str__(self):
        return self.comment

영화리뷰/devsns/snsapp/forms.py
from django import forms
from .models import Post, Comment, FreePost, FreeComment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20
        }

        self.fields['body'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20,
            'cols' : 100
        }
        # 자동으로 생성되는 html 태그들에 특정 클래스(부트스트랩)를 설정해주기 위해선 위처럼 widget을 사용해줘야 함
        # widget을 사용하기 위해서 생성자를 만들어줌

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs={
            'class':'form-control',
            'placeholder': "댓글을 입력해주세요",
            'rows':10
        }

class FreePostForm(forms.ModelForm):
    class Meta:
        model = FreePost
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(FreePostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20
        }

        self.fields['body'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20,
            'cols' : 100
        }

class FreeCommentForm(forms.ModelForm):
    class Meta:
        model = FreeComment
        fields = ['comment']
    def __init__(self, *args, **kwargs):
        super(FreeCommentForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs={
            'class':'form-control',
            'placeholder': "댓글을 입력해주세요",
            'rows':10
        }

영화리뷰/devsns/snsapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm, FreePostForm, FreeCommentForm
from .models import Post, FreePost
from django.core.paginator import Paginator

######## 익명게시판 ##################
def home(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 5) #5개 단위로 페이지를 끊어줄꺼다
    pagnum = request.GET.get('page') #딕셔너리 형태로 담겨있음, 페이지에 매칭되는 숫자를 가져와라
    posts = paginator.get_page(pagnum)
    return render(request, 'index.html', {'posts':posts})

def postcreate(request):
    # request method가 post일 경우
    # 입력값 저장
    if request.method == 'POST' or request.method == 'FILES':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')

    # request method가 get일 경우
    # form 입력 html 띄우기
    else:
        form = PostForm()
    return render(request, 'post_form.html', {'form': form})

# 상세보기
def detail(request, post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm()
    return render(request, 'detail.html', {'post_detail':post_detail, 'comment_form':comment_form})

# 댓글을 저장해줌
def new_comment(request, post_id):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False) # 어떤 post의 댓글인지 모르니 아직은 저장하지 말고 기다려
        finished_form.post = get_object_or_404(Post, pk=post_id)
        finished_form.save() # 저장해~
    return redirect('detail', post_id)



####### 자유게시판 ######################

def freehome(request):
    freeposts = FreePost.objects.all()
    return render(request, 'free_index.html', {'freeposts': freeposts})

def freepostcreate(request):
    # request method가 post일 경우 입력값 저장
    if request.method == 'POST' or request.method == 'FILES':
        form = FreePostForm(request.POST, request.FILES)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.author = request.user #작성자 추가
            unfinished.save()
            return redirect('freehome')

    # request method가 get일 경우 form 입력 html 띄우기
    else:
        form = FreePostForm()
    return render(request, 'free_post_form.html', {'form': form})

# 상세보기
def freedetail(request, post_id):
    post_detail = get_object_or_404(FreePost, pk=post_id)
    comment_form = FreeCommentForm()
    return render(request, 'free_detail.html', {'post_detail':post_detail, 'comment_form':comment_form})

# 댓글을 저장해줌
def new_freecomment(request, post_id):
    filled_form = FreeCommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False) # 어떤 post의 댓글인지 모르니 아직은 저장하지 말고 기다려
        finished_form.post = get_object_or_404(Post, pk=post_id)
        finished_form.save() # 저장해~
    return redirect('freedetail', post_id)

# 통계
def stat(request):
    return render(request, 'stat.html')

영화리뷰/devsns/snsapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>개발자 대나무숲</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">개발자 대나무숲</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>익명게시판</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'freehome' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>자유게시판</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-success" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% if user.is_authenticated %}<!--현재 로그인한 유저라면-->
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                                {% else %} <!--현재 로그인이 되어있지 않다면-->
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">로그인</span>
                                {% endif %}
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">

                                {% if user.is_authenticated %} <!--현재 로그인한 유저라면-->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                                {% else %} <!--현재 로그인이 되어있지 않다면-->
                                <a class="dropdown-item" href="{% url 'login' %}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Login
                                </a>
                                {% endif %}
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                {% block content %}
                
                {% endblock %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">로그아웃하시겠어요?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">아래 로그아웃 버튼을 눌러주세요.</div>
                <div class="modal-footer">
                    <a class="btn btn-success" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

영화리뷰/devsns/snsapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<h2 class="alert alert-primary"> {{ post_detail.title }}</h2>
<span class="badge rounded-pill bg-light">{{ post_detail.date}}</span>
<br/><hr/>
<p>
    {{ post_detail.body }}
</p>
<!-- 이미지 보여주기 -->
{% if post_detail.photo %}
    <img src = "{{ post_detail.photo.url }}" alt="" height="600">
<br>
{% endif %}
<br/><hr/>

<!-- 댓글 목록 공간 
{% for comment in post_detail.comment_set.all %} 
    <span class="badge rounded-pill bg-light">{{ comment.date}}</span>    
    {{ comment }}
    <hr>
{% endfor %}

댓글 입력 공간 
<form method="POST" action="{% url 'new_comment' post_detail.id  %}">
    {% csrf_token %}
    <div class="form-group">
        {{ comment_form }}
    </div>
    <input type="submit" class="btn btn-primary btn-icon-split btn-sm" value="댓글 입력">
</form>
-->

{% endblock %}

영화리뷰/devsns/snsapp/templates/free_detail.html
{% extends 'base.html' %}

{% block content %}
<h2 class="alert alert-success"> {{ post_detail.title }}</h2>
<span class="badge rounded-pill bg-light">{{ post_detail.date}}</span>
<br/>
<span class="badge rounded-pill bg-light">{{ post_detail.author.username}}</span>
<hr/>
<p>
    {{ post_detail.body }}
</p>
<br/><hr/>
<!-- 댓글 목록 공간 -->
{% for comment in post_detail.freecomment_set.all %}
<span class="badge rounded-pill bg-light">{{ comment.date}}</span>    
{{ comment }}
<hr>
{% endfor %}

<!-- 댓글 입력 공간 -->
<form method="POST" action="{% url 'new_freecomment' post_detail.id  %}">
    {% csrf_token %}
    <div class="form-group">
        {{ comment_form }}
    </div>
    <input type="submit" class="btn btn-success btn-icon-split btn-sm" value="댓글 입력">
</form>

{% endblock %}

영화리뷰/devsns/snsapp/templates/free_index.html
{% extends 'base.html' %}
{% block content %}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-success">자유게시판</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in freeposts %}
                    <tr>
                        <td><a href="{% url 'freedetail' post.id %}">{{ post.title }}</a></td>
                        <td>{{ post.date }}</td>
                        <td>{{ post.author.username }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
{% if user.is_authenticated %}
<a href="{% url 'freepostcreate' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>
{% endif %}
{% endblock %}

영화리뷰/devsns/snsapp/templates/free_post_form.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_p}}
    </table>
    <br/>
    <input type="submit" class="btn btn-success btn-icon-split btn-sm" value="create">
</form>
{% endblock %}

영화리뷰/devsns/snsapp/templates/index.html
{% extends 'base.html' %}
{% block content %}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-success">익명게시판</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>글 제목</th>
                        <th>작성 날짜</th>
                        <th>익명</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'detail' post.id %}">{{ post.title }}</a></td>
                        <td>{{ post.date }}</td>
                        <img src = "{{ post.photo}}" alt="" >  
                        <td>{% if post.photo %}
                                <img src = "{{ post.photo}}" alt="" >           
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% for post in posts %}
            <a href="{% url 'detail' post.id %}">{{ post.title }}</a>
            {{ post.date }}

                        {% if post.photo %}
                                <img src = "{{ post.photo.url }}" alt=""height="100" >           
                            {% endif %}
                        
                    <br/>
                    {% endfor %}
        </div>
    </div>
</div>
</div>
{% if user.is_authenticated %}
<a href="{% url 'postcreate' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>
{% endif %}
<!--페이지네이션-->
{% if posts.has_previous %} <!--이전페이지가 있다면-->
<a href="?page=1"> 첫 페이지</a>
<a href="?page={{posts.previous_page_number}}">이전 페이지</a>
{%endif%}
<span> {{posts.number}}</span>
<span>/</span>
<span> {{posts.paginator.num_pages}}</span>
{% if posts.has_next %} <!--다음페이지가 있다면-->
<a href="?page={{posts.next_page_number}}"> 다음 페이지</a>
<a href="?page={{posts.paginator.num_pages}}">마지막 페이지</a>
{%endif%}
{% endblock %}

영화리뷰/devsns/snsapp/templates/post_form.html
{% extends 'base.html' %}
{% block content %}
<h1> 새 글 작성</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="작성 완료">
</form>
{% endblock %}